#图像识别文字功能配置
duoduo:
  baidu:
    ocr:
      appId: 16177245
      apiKey: jmYqeL8TK5Gu4mFx7XEhV2qH
      secretKey: DML8mWGt0KwFluGMnOjM3T2n5nLfO8DE
    token:
      url: https://aip.baidubce.com/oauth/2.0/token
      grantType: client_credentials
    urlMap:
       general_basic:
         url: https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic
         method: 1
       accurate_basic:
         url: https://aip.baidubce.com/rest/2.0/ocr/v1/accurate_basic
         method: 1

#端口
server:
  port: 8888
#数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/duoduo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #redis配置
  redis:
    host: 127.0.0.1
  security:
    user:
      name: root
      password: root
#  security:
#    user:
#      name: root
#      password: root
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.duoduo.**.entity
  #typeEnumsPackage: com.duoduo.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    #id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    table-prefix: t_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    #logic-delete-value: 1
    #logic-not-delete-value: 0

  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    #jdbc-type-for-null: 'null'

